run:
	echo "This program need to be compiled with C++20 and above also g++ version should be 	g++ (Ubuntu 12.1.0-2ubuntu1~22.04) 12.1.0"
	g++ -std=c++2a -Wall -Wextra -Wpedantic main.cpp ./include/thread_safe_set.hpp ./src/custom_type.cpp -o executable
